spring:
  application:
    name: schoolregistration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${schoolregistration.database.url}:schoolregistration?createDatabaseIfNotExist=true
    username:  ${spring.datasource.username}
    password: ${spring.datasource.password}
    maxPoolSize: 10
    minPoolSize: 3
    maxIdleTime: 6000

  jpa:
    database:
    show-sql: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback-spring.xml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    doc-expansion: none

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-headers: '*'
        allowed-methods: GET, OPTIONS
        exposed-headers: 'Access-Control-Allow-Origin, Access-Control-Allow-Credentials'

controller:
  exception:
    handler:
      default-enabled: true

server:
  error:
    include-message: always